version: 0.0.{build}

branches:
  only:
    - master

skip_tags: true

image:
  - Visual Studio 2017

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

build_script:
  - cmd: dotnet build --configuration Release --verbosity quiet
  - cmd: dotnet pack ./ScraperSharp/ScraperSharp.csproj --configuration Release --no-restore --no-build --verbosity quiet

test:
  assemblies:
    only:
      - ScraperSharp\bin\Release\netcoreapp2.1\ScraperSharp.dll

artifacts:
  - path: '**\*.nupkg'

deploy:
  - provider: NuGet
    api_key:
      secure: hUkhIXTpdjZMy2lopC8rAa2AvIHRa7hTF2M2neTrgh3FTSgxtuiGHWfl9WcTsz6+
    skip_symbols: true
    artifact: /.*\.nupkg/